// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://quvehhofhznnexgzqugv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1dmVoaG9maHpubmV4Z3pxdWd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3Mjk0ODUsImV4cCI6MjA1NjMwNTQ4NX0.Fx3Xf6iK9JgPrxsxSSAwNYOW_pbjdw64fs7uRxQnyp4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);